/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    CategoryComponent: typeof import('./src/components/CategoryComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
